# Generated by Django 5.2.4 on 2025-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="issued_by",
        ),
        migrations.AddField(
            model_name="libid",
            name="issued_book",
            field=models.ManyToManyField(related_name="stu_info", to="app.books"),
        ),
    ]
