# Generated by Django 5.2.4 on 2025-07-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=25)),
                ("l_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.IntegerField()),
                ("password", models.CharField(max_length=25)),
            ],
        ),
    ]
