# Generated by Django 5.2.5 on 2025-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to="img/"),
        ),
    ]
