# Generated by Django 5.2.4 on 2025-07-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.IntegerField()),
                ("image", models.ImageField(upload_to="img/")),
                ("document", models.FileField(upload_to="file/")),
                ("password", models.CharField(max_length=25)),
            ],
        ),
    ]
