# Generated by Django 5.2.4 on 2025-07-08 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="name",
            new_name="first_name",
        ),
    ]
